---
title: "Plot Level 4 units based on marine provinces (MEOW) and mangrove biophysical type data"
editor_options:
  chunk_output_type: console
---


We intersected the polygon of _Marine provinces_ from [MEOW](https://www.worldwildlife.org/publications/marine-ecoregions-of-the-world-a-bioregionalization-of-coastal-and-shelf-areas) and species distribution records from GBIF

Load libraries

```{r}
```



Preview list of associated species
```{r}
head(res)
table(res$kingdom_name,res$habitat)

res %>% group_by(class_name) %>% summarise(total=n_distinct(scientific_name))

res %>% group_by(order_name) %>% summarise(total=n_distinct(scientific_name))
res %>% group_by(order_name) %>% summarise(total=n_distinct(scientific_name)) %>% arrange(desc(total))
```

Check first how many records are available in GBIF for each species:

```{r}


summary(res$gbif_records)
summary(res$gbif_xy_records)
```


```{r}
```


```{r}

```


```{r}


```

and other species...

```{r}
```


```{r}


all_occs <- ls(pattern="occ_data")
lst <- mget(all_occs)

gbif_qry <- bind_cols(
  order_names=gsub("occ_data_","",names(lst)),
  found=sapply(lst,function(x) x$gbif$meta$found,simplify=T), returned=sapply(lst,function(x) x$gbif$meta$returned,simplify=T))

gbif_qry %>% filter(found<=returned) %>% pull(order_names) -> listos
gbif_qry %>% filter(found<(2*returned) & !(order_names %in% listos))

tst <- occ2df(occ_data_ACCIPITRIFORMES) 
plot(latitude~longitude,tst)

#occ_data$gbif$data$Zenarchopterus_buffonis %>% select(longitude,latitude,countrycode,higherGeography)

```
